package main

import (
	"encoding/json"
	"net/http"
)

var codes = map[string]string{
	"Afghanistan":                         "af",
	"Aland Islands":                       "ax",
	"Albania":                             "al",
	"Algeria":                             "dz",
	"American Samoa":                      "as",
	"Andorra":                             "ad",
	"Angola":                              "ao",
	"Anguilla":                            "ai",
	"Antigua and Barbuda":                 "ag",
	"Argentina":                           "ar",
	"Armenia":                             "am",
	"Aruba":                               "aw",
	"Australia":                           "au",
	"Austria":                             "at",
	"Azerbaijan":                          "az",
	"Bahamas":                             "bs",
	"Bahrain":                             "bh",
	"Baker Island":                        "us",
	"Bangladesh":                          "bd",
	"Barbados":                            "bb",
	"Belarus":                             "by",
	"Belgium":                             "be",
	"Belize":                              "bz",
	"Benin":                               "bj",
	"Bermuda":                             "bm",
	"Bhutan":                              "bt",
	"Bolivia":                             "bo",
	"Bonaire, Saint Eustachius and Saba":  "bq",
	"Bosnia and Herzegovina":              "ba",
	"Botswana":                            "bw",
	"Bouvet Island":                       "bv",
	"Brazil":                              "br",
	"British Indian Ocean Territory":      "io",
	"British Virgin Islands":              "vg",
	"Brunei Darussalam":                   "bn",
	"Bulgaria":                            "bg",
	"Burkina Faso":                        "bf",
	"Burundi":                             "bi",
	"Cambodia":                            "kh",
	"Cameroon":                            "cm",
	"Canada":                              "ca",
	"Cape Verde":                          "cv",
	"Cayman Islands":                      "ky",
	"Central African Republic":            "cf",
	"Chad":                                "td",
	"Chile":                               "cl",
	"China":                               "cn",
	"Christmas Island":                    "cx",
	"Cocos (Keeling) Islands":             "cc",
	"Colombia":                            "co",
	"Comoros":                             "km",
	"Cook Islands":                        "ck",
	"Costa Rica":                          "cr",
	"Croatia":                             "hr",
	"Cuba":                                "cu",
	"Curaçao":                             "cw",
	"Cyprus":                              "cy",
	"Czech Republic":                      "cz",
	"Côte d'Ivoire":                       "ci",
	"Democratic Republic of Congo":        "cd",
	"Denmark":                             "dk",
	"Djibouti":                            "dj",
	"Dominica":                            "dm",
	"Dominican Republic":                  "do",
	"Ecuador":                             "ec",
	"Egypt":                               "eg",
	"El Salvador":                         "sv",
	"Equatorial Guinea":                   "gq",
	"Eritrea":                             "er",
	"Estonia":                             "ee",
	"Ethiopia":                            "et",
	"Falkland Islands":                    "fk",
	"Faroe Islands":                       "fo",
	"Federated States of Micronesia":      "fm",
	"Fiji":                                "fj",
	"Finland":                             "fi",
	"France":                              "fr",
	"French Guiana":                       "gf",
	"French Polynesia":                    "pf",
	"French Southern and Antarctic Lands": "tf",
	"Gabon":                               "ga",
	"Gambia":                              "gm",
	"Georgia":                             "ge",
	"Germany":                             "de",
	"Ghana":                               "gh",
	"Gibraltar":                           "gi",
	"Glorioso Islands":                    "tf",
	"Greece":                              "gr",
	"Greenland":                           "gl",
	"Grenada":                             "gd",
	"Guadeloupe":                          "gp",
	"Guam":                                "gu",
	"Guatemala":                           "gt",
	"Guernsey":                            "gg",
	"Guinea":                              "gn",
	"Guinea-Bissau":                       "gw",
	"Guyana":                              "gy",
	"Haiti":                               "ht",
	"Heard Island and McDonald Islands":   "hm",
	"Honduras":                            "hn",
	"Hong Kong":                           "hk",
	"Howland Island":                      "us",
	"Hungary":                             "hu",
	"Iceland":                             "is",
	"India":                               "in",
	"Indonesia":                           "id",
	"Iran":                                "ir",
	"Iraq":                                "iq",
	"Ireland":                             "ie",
	"Isle of Man":                         "im",
	"Israel":                              "il",
	"Italy":                               "it",
	"Jamaica":                             "jm",
	"Japan":                               "jp",
	"Jarvis Island":                       "us",
	"Jersey":                              "je",
	"Johnston Atoll":                      "us",
	"Jordan":                              "jo",
	"Juan De Nova Island":                 "tf",
	"Kazakhstan":                          "kz",
	"Kenya":                               "ke",
	"Kiribati":                            "ki",
	"Kosovo":                              "xk",
	"Kuwait":                              "kw",
	"Kyrgyzstan":                          "kg",
	"Lao People's Democratic Republic":    "la",
	"Latvia":                              "lv",
	"Lebanon":                             "lb",
	"Lesotho":                             "ls",
	"Liberia":                             "lr",
	"Libya":                               "ly",
	"Liechtenstein":                       "li",
	"Lithuania":                           "lt",
	"Luxembourg":                          "lu",
	"Macau":                               "mo",
	"Macedonia":                           "mk",
	"Madagascar":                          "mg",
	"Malawi":                              "mw",
	"Malaysia":                            "my",
	"Maldives":                            "mv",
	"Mali":                                "ml",
	"Malta":                               "mt",
	"Marshall Islands":                    "mh",
	"Martinique":                          "mq",
	"Mauritania":                          "mr",
	"Mauritius":                           "mu",
	"Mayotte":                             "yt",
	"Mexico":                              "mx",
	"Midway Islands":                      "us",
	"Moldova":                             "md",
	"Monaco":                              "mc",
	"Mongolia":                            "mn",
	"Montenegro":                          "me",
	"Montserrat":                          "ms",
	"Morocco":                             "ma",
	"Mozambique":                          "mz",
	"Myanmar":                             "mm",
	"Namibia":                             "na",
	"Nauru":                               "nr",
	"Nepal":                               "np",
	"Netherlands":                         "nl",
	"New Caledonia":                       "nc",
	"New Zealand":                         "nz",
	"Nicaragua":                           "ni",
	"Niger":                               "ne",
	"Nigeria":                             "ng",
	"Niue":                                "nu",
	"Norfolk Island":                      "nf",
	"North Korea":                         "kp",
	"Northern Mariana Islands":            "mp",
	"Norway":                              "no",
	"Oman":                                "om",
	"Pakistan":                            "pk",
	"Palau":                               "pw",
	"Palestinian Territories":             "ps",
	"Panama":                              "pa",
	"Papua New Guinea":                    "pg",
	"Paraguay":                            "py",
	"Peru":                                "pe",
	"Philippines":                         "ph",
	"Pitcairn Islands":                    "pn",
	"Poland":                              "pl",
	"Portugal":                            "pt",
	"Puerto Rico":                         "pr",
	"Qatar":                               "qa",
	"Republic of Congo":                   "cg",
	"Reunion":                             "re",
	"Romania":                             "ro",
	"Russia":                              "ru",
	"Rwanda":                              "rw",
	"Saint Barthelemy":                    "bl",
	"Saint Helena":                        "sh",
	"Saint Kitts and Nevis":               "kn",
	"Saint Lucia":                         "lc",
	"Saint Martin":                        "mf",
	"Saint Pierre and Miquelon":           "pm",
	"Saint Vincent and the Grenadines":    "vc",
	"Samoa":                               "ws",
	"San Marino":                          "sm",
	"Sao Tome and Principe":               "st",
	"Saudi Arabia":                        "sa",
	"Senegal":                             "sn",
	"Serbia":                              "rs",
	"Seychelles":                          "sc",
	"Sierra Leone":                        "sl",
	"Singapore":                           "sg",
	"Slovakia":                            "sk",
	"Slovenia":                            "si",
	"Solomon Islands":                     "sb",
	"Somalia":                             "so",
	"South Africa":                        "za",
	"South Georgia and South Sandwich Islands": "gs",
	"South Korea":              "kr",
	"South Sudan":              "ss",
	"Spain":                    "es",
	"Sri Lanka":                "lk",
	"Sudan":                    "sd",
	"Suriname":                 "sr",
	"Svalbard and Jan Mayen":   "sj",
	"Swaziland":                "sz",
	"Sweden":                   "se",
	"Switzerland":              "ch",
	"Syria":                    "sy",
	"Taiwan":                   "tw",
	"Tajikistan":               "tj",
	"Tanzania":                 "tz",
	"Thailand":                 "th",
	"Timor-Leste":              "tl",
	"Togo":                     "tg",
	"Tokelau":                  "tk",
	"Tonga":                    "to",
	"Trinidad and Tobago":      "tt",
	"Tunisia":                  "tn",
	"Turkey":                   "tr",
	"Turkmenistan":             "tm",
	"Turks and Caicos Islands": "tc",
	"Tuvalu":                   "tv",
	"US Virgin Islands":        "vi",
	"Uganda":                   "ug",
	"Ukraine":                  "ua",
	"United Arab Emirates":     "ae",
	"United Kingdom":           "gb",
	"United States":            "us",
	"Uruguay":                  "uy",
	"Uzbekistan":               "uz",
	"Vanuatu":                  "vu",
	"Vatican City":             "va",
	"Venezuela":                "ve",
	"Vietnam":                  "vn",
	"Wake Island":              "us",
	"Wallis and Futuna":        "wf",
	"Western Sahara":           "eh",
	"Yemen":                    "ye",
	"Zambia":                   "zm",
	"Zimbabwe":                 "zw",
}

// GetCodes gets the map of country name to ISO-3166 code.
func GetCodes(writer http.ResponseWriter, request *http.Request) {
	json.NewEncoder(writer).Encode(codes)
}
