package main

import (
	"encoding/json"
	"net/http"
)

var countries = []string{
	"afghanistan",
	"albania",
	"algeria",
	"andorra",
	"angola",
	"antigua and barbuda",
	"argentina",
	"armenia",
	"australia",
	"austria",
	"azerbaijan",
	"bahamas",
	"bahrain",
	"bangladesh",
	"barbados",
	"belarus",
	"belgium",
	"belize",
	"benin",
	"bhutan",
	"bolivia",
	"bosnia and herzegovina",
	"botswana",
	"brazil",
	"brunei",
	"bulgaria",
	"burkina faso",
	"burundi",
	"cambodia",
	"cameroon",
	"canada",
	"cape verde",
	"central african republic",
	"chad",
	"chile",
	"china",
	"colombia",
	"comoros",
	"costa rica",
	"croatia",
	"cuba",
	"cyprus",
	"czech republic",
	"cote d'ivoire",
	"democratic republic of congo",
	"denmark",
	"djibouti",
	"dominica",
	"dominican republic",
	"ecuador",
	"egypt",
	"el salvador",
	"equatorial guinea",
	"eritrea",
	"estonia",
	"ethiopia",
	"federated states of micronesia",
	"fiji",
	"finland",
	"france",
	"gabon",
	"gambia",
	"georgia",
	"germany",
	"ghana",
	"greece",
	"grenada",
	"guatemala",
	"guinea",
	"guinea-bissau",
	"guyana",
	"haiti",
	"honduras",
	"hungary",
	"iceland",
	"india",
	"indonesia",
	"iran",
	"iraq",
	"ireland",
	"israel",
	"italy",
	"jamaica",
	"japan",
	"jordan",
	"kazakhstan",
	"kenya",
	"kiribati",
	"kosovo",
	"kuwait",
	"kyrgyzstan",
	"lao people's democratic republic",
	"latvia",
	"lebanon",
	"lesotho",
	"liberia",
	"libya",
	"liechtenstein",
	"lithuania",
	"luxembourg",
	"macedonia",
	"madagascar",
	"malawi",
	"malaysia",
	"maldives",
	"mali",
	"malta",
	"marshall islands",
	"mauritania",
	"mauritius",
	"mexico",
	"moldova",
	"monaco",
	"mongolia",
	"montenegro",
	"morocco",
	"mozambique",
	"myanmar",
	"namibia",
	"nauru",
	"nepal",
	"netherlands",
	"new zealand",
	"nicaragua",
	"niger",
	"nigeria",
	"north korea",
	"norway",
	"oman",
	"pakistan",
	"palau",
	"palestinian territories",
	"panama",
	"papua new guinea",
	"paraguay",
	"peru",
	"philippines",
	"poland",
	"portugal",
	"qatar",
	"republic of congo",
	"romania",
	"russia",
	"rwanda",
	"saint kitts and nevis",
	"saint lucia",
	"saint vincent and the grenadines",
	"samoa",
	"san marino",
	"sao tome and principe",
	"saudi arabia",
	"senegal",
	"serbia",
	"seychelles",
	"sierra leone",
	"singapore",
	"slovakia",
	"slovenia",
	"solomon islands",
	"somalia",
	"south africa",
	"south korea",
	"south sudan",
	"spain",
	"sri lanka",
	"sudan",
	"suriname",
	"swaziland",
	"sweden",
	"switzerland",
	"syria",
	"taiwan",
	"tajikistan",
	"tanzania",
	"thailand",
	"timor-leste",
	"togo",
	"tonga",
	"trinidad and tobago",
	"tunisia",
	"turkey",
	"turkmenistan",
	"tuvalu",
	"uganda",
	"ukraine",
	"united arab emirates",
	"united kingdom",
	"united states",
	"uruguay",
	"uzbekistan",
	"vanuatu",
	"vatican city",
	"venezuela",
	"vietnam",
	"yemen",
	"zambia",
	"zimbabwe",
}

var alternativeNamings = []string{
	"côte d'ivoire",
	"ivory coast",
	"laos",
	"palestine",
	"cabo verde",
	"czechia",
	"micronesia",
	"car",
	"congo, democratic republic of the",
	"drc",
	"republic of the congo",
	"congo, republic of the",
	"eswatini",
	"burma",
	"north macedonia",
	"uae",
	"uk",
	"usa",
	"holy see",
}

var prefixes = map[string]string{
	"uk":       "Ukraine",
	"niger":    "Nigeria",
	"dominica": "Dominican Republic",
}

var countriesMap = map[string]string{
	"afghanistan":                       "Afghanistan",
	"albania":                           "Albania",
	"algeria":                           "Algeria",
	"andorra":                           "Andorra",
	"angola":                            "Angola",
	"antigua and barbuda":               "Antigua and Barbuda",
	"argentina":                         "Argentina",
	"armenia":                           "Armenia",
	"australia":                         "Australia",
	"austria":                           "Austria",
	"azerbaijan":                        "Azerbaijan",
	"bahamas":                           "Bahamas",
	"bahrain":                           "Bahrain",
	"bangladesh":                        "Bangladesh",
	"barbados":                          "Barbados",
	"belarus":                           "Belarus",
	"belgium":                           "Belgium",
	"belize":                            "Belize",
	"benin":                             "Benin",
	"bhutan":                            "Bhutan",
	"bolivia":                           "Bolivia",
	"bosnia and herzegovina":            "Bosnia and Herzegovina",
	"botswana":                          "Botswana",
	"brazil":                            "Brazil",
	"brunei":                            "Brunei Darussalam",
	"bulgaria":                          "Bulgaria",
	"burkina faso":                      "Burkina Faso",
	"burundi":                           "Burundi",
	"cambodia":                          "Cambodia",
	"cameroon":                          "Cameroon",
	"canada":                            "Canada",
	"cape verde":                        "Cape Verde",
	"cabo verde":                        "Cape Verde",
	"central african republic":          "Central African Republic",
	"car":                               "Central African Republic",
	"chad":                              "Chad",
	"chile":                             "Chile",
	"china":                             "China",
	"colombia":                          "Colombia",
	"comoros":                           "Comoros",
	"costa rica":                        "Costa Rica",
	"croatia":                           "Croatia",
	"cuba":                              "Cuba",
	"cyprus":                            "Cyprus",
	"czech republic":                    "Czech Republic",
	"czechia":                           "Czech Republic",
	"côte d'ivoire":                     "Côte d'Ivoire",
	"cote d'ivoire":                     "Côte d'Ivoire",
	"ivory coast":                       "Côte d'Ivoire",
	"democratic republic of congo":      "Democratic Republic of Congo",
	"congo, democratic republic of the": "Democratic Republic of Congo",
	"drc":                               "Democratic Republic of Congo",
	"denmark":                           "Denmark",
	"djibouti":                          "Djibouti",
	"dominica":                          "Dominica",
	"dominican republic":                "Dominican Republic",
	"ecuador":                           "Ecuador",
	"egypt":                             "Egypt",
	"el salvador":                       "El Salvador",
	"equatorial guinea":                 "Equatorial Guinea",
	"eritrea":                           "Eritrea",
	"estonia":                           "Estonia",
	"ethiopia":                          "Ethiopia",
	"federated states of micronesia":    "Federated States of Micronesia",
	"micronesia":                        "Federated States of Micronesia",
	"fiji":                              "Fiji",
	"finland":                           "Finland",
	"france":                            "France",
	"gabon":                             "Gabon",
	"gambia":                            "Gambia",
	"georgia":                           "Georgia",
	"germany":                           "Germany",
	"ghana":                             "Ghana",
	"greece":                            "Greece",
	"grenada":                           "Grenada",
	"guatemala":                         "Guatemala",
	"guinea":                            "Guinea",
	"guinea-bissau":                     "Guinea-Bissau",
	"guyana":                            "Guyana",
	"haiti":                             "Haiti",
	"honduras":                          "Honduras",
	"hungary":                           "Hungary",
	"iceland":                           "Iceland",
	"india":                             "India",
	"indonesia":                         "Indonesia",
	"iran":                              "Iran",
	"iraq":                              "Iraq",
	"ireland":                           "Ireland",
	"israel":                            "Israel",
	"italy":                             "Italy",
	"jamaica":                           "Jamaica",
	"japan":                             "Japan",
	"jordan":                            "Jordan",
	"kazakhstan":                        "Kazakhstan",
	"kenya":                             "Kenya",
	"kiribati":                          "Kiribati",
	"kosovo":                            "Kosovo",
	"kuwait":                            "Kuwait",
	"kyrgyzstan":                        "Kyrgyzstan",
	"lao people's democratic republic":  "Lao People's Democratic Republic",
	"laos":                              "Lao People's Democratic Republic",
	"latvia":                            "Latvia",
	"lebanon":                           "Lebanon",
	"lesotho":                           "Lesotho",
	"liberia":                           "Liberia",
	"libya":                             "Libya",
	"liechtenstein":                     "Liechtenstein",
	"lithuania":                         "Lithuania",
	"luxembourg":                        "Luxembourg",
	"macedonia":                         "Macedonia",
	"north macedonia":                   "Macedonia",
	"madagascar":                        "Madagascar",
	"malawi":                            "Malawi",
	"malaysia":                          "Malaysia",
	"maldives":                          "Maldives",
	"mali":                              "Mali",
	"malta":                             "Malta",
	"marshall islands":                  "Marshall Islands",
	"mauritania":                        "Mauritania",
	"mauritius":                         "Mauritius",
	"mexico":                            "Mexico",
	"moldova":                           "Moldova",
	"monaco":                            "Monaco",
	"mongolia":                          "Mongolia",
	"montenegro":                        "Montenegro",
	"morocco":                           "Morocco",
	"mozambique":                        "Mozambique",
	"myanmar":                           "Myanmar",
	"burma":                             "Myanmar",
	"namibia":                           "Namibia",
	"nauru":                             "Nauru",
	"nepal":                             "Nepal",
	"netherlands":                       "Netherlands",
	"new zealand":                       "New Zealand",
	"nicaragua":                         "Nicaragua",
	"niger":                             "Niger",
	"nigeria":                           "Nigeria",
	"north korea":                       "North Korea",
	"norway":                            "Norway",
	"oman":                              "Oman",
	"pakistan":                          "Pakistan",
	"palau":                             "Palau",
	"palestinian territories":           "Palestinian Territories",
	"palestine":                         "Palestinian Territories",
	"panama":                            "Panama",
	"papua new guinea":                  "Papua New Guinea",
	"paraguay":                          "Paraguay",
	"peru":                              "Peru",
	"philippines":                       "Philippines",
	"poland":                            "Poland",
	"portugal":                          "Portugal",
	"qatar":                             "Qatar",
	"republic of congo":                 "Republic of Congo",
	"republic of the congo":             "Republic of Congo",
	"congo, the republic of the":        "Republic of Congo",
	"romania":                           "Romania",
	"russia":                            "Russia",
	"rwanda":                            "Rwanda",
	"saint kitts and nevis":             "Saint Kitts and Nevis",
	"saint lucia":                       "Saint Lucia",
	"saint vincent and the grenadines":  "Saint Vincent and the Grenadines",
	"samoa":                             "Samoa",
	"san marino":                        "San Marino",
	"sao tome and principe":             "Sao Tome and Principe",
	"saudi arabia":                      "Saudi Arabia",
	"senegal":                           "Senegal",
	"serbia":                            "Serbia",
	"seychelles":                        "Seychelles",
	"sierra leone":                      "Sierra Leone",
	"singapore":                         "Singapore",
	"slovakia":                          "Slovakia",
	"slovenia":                          "Slovenia",
	"solomon islands":                   "Solomon Islands",
	"somalia":                           "Somalia",
	"south africa":                      "South Africa",
	"south korea":                       "South Korea",
	"south sudan":                       "South Sudan",
	"spain":                             "Spain",
	"sri lanka":                         "Sri Lanka",
	"sudan":                             "Sudan",
	"suriname":                          "Suriname",
	"swaziland":                         "Swaziland",
	"eswatini":                          "Swaziland",
	"sweden":                            "Sweden",
	"switzerland":                       "Switzerland",
	"syria":                             "Syria",
	"taiwan":                            "Taiwan",
	"tajikistan":                        "Tajikistan",
	"tanzania":                          "Tanzania",
	"thailand":                          "Thailand",
	"timor-leste":                       "Timor-Leste",
	"togo":                              "Togo",
	"tonga":                             "Tonga",
	"trinidad and tobago":               "Trinidad and Tobago",
	"tunisia":                           "Tunisia",
	"turkey":                            "Turkey",
	"turkmenistan":                      "Turkmenistan",
	"tuvalu":                            "Tuvalu",
	"uganda":                            "Uganda",
	"ukraine":                           "Ukraine",
	"united arab emirates":              "United Arab Emirates",
	"uae":                               "United Arab Emirates",
	"united kingdom":                    "United Kingdom",
	"uk":                                "United Kingdom",
	"united states":                     "United States",
	"usa":                               "United States",
	"uruguay":                           "Uruguay",
	"uzbekistan":                        "Uzbekistan",
	"vanuatu":                           "Vanuatu",
	"vatican city":                      "Vatican City",
	"holy see":                          "Vatican City",
	"venezuela":                         "Venezuela",
	"vietnam":                           "Vietnam",
	"yemen":                             "Yemen",
	"zambia":                            "Zambia",
	"zimbabwe":                          "Zimbabwe",
}

// GetCountries gets the list of accepted countries.
func GetCountries(writer http.ResponseWriter, request *http.Request) {
	json.NewEncoder(writer).Encode(countries)
}

// GetAlternativeNamings gets the list of alternative names for countries.
func GetAlternativeNamings(writer http.ResponseWriter, request *http.Request) {
	json.NewEncoder(writer).Encode(alternativeNamings)
}

// GetPrefixes gets the map of the prefix submission to alternative country name.
func GetPrefixes(writer http.ResponseWriter, request *http.Request) {
	json.NewEncoder(writer).Encode(prefixes)
}

// GetCountriesMap gets the map of country name to correctly formatted name used in the SVG map.
func GetCountriesMap(writer http.ResponseWriter, request *http.Request) {
	json.NewEncoder(writer).Encode(countriesMap)
}
